0 "memory" "" "Virtual(Alloc|Free|Protect)"
0 "memory" "" "(Nt)?ProtectVirtualMemory"
0 "memory" "" "(Nt)?AllocateVirtualMemory"
0 "memory" "" "(Nt)?WriteVirtualMemory"
0 "memory" "" "(Zw)?MapViewOfSection"
0 "memory" "" "(Nt)?UnmapViewOfSection"
0 "memory" "" "(Zw)?ReadVirtualMemory"

0 "memory" "" "Heap(Re)?Alloc"
0 "memory" "" "Heap(Create|Free|SetInformation|Size)"
0 "memory" "" "GetProcessHeap"
